### ISSUE TITLE
Куки spravka отсутствует на сайте

### ISSUE THREAD

**Issue by inexcode** [llistochek/yandex-music-downloader#1]
Проверял в нескольких браузерах, куки `spravka` не предоставляется. Если убрать её из скрипта, то скрипт в целом работает, пока не упирается в капчу.

**Comment by llistochek** [comment]
Действительно, `spravka` выдается каким-то непонятным образом. Сделаю данный аргумент необязательным. Без него скрипт работает нормально, при довольно больших задержках `--delay` (больше 2х секунд).

**Comment by llistochek** [comment]
Исправлено в bf171eef5c6a7753df9fd3f10cb8818eb7a216aa
