### ISSUE TITLE
KeyError: 'year'

### ISSUE THREAD

**Issue by Catangenss** [llistochek/yandex-music-downloader#10]
При попытке скачать свой основной плейлист получаю вот это:

File "/home/***/yamusic/yandex-music-downloader/main.py", line 78, in from_json
    return BasicAlbumInfo(id=json['id'], title=title, year=json['year'],
KeyError: 'year'

Некоторые остальные плейлисты тоже не скачивает, самый крохотный удалось скачать.

**Comment by llistochek** [comment]
Исправил. Возникали ли еще какие нибудь ошибки кроме `KeyError: 'year'`?

**Comment by Catangenss** [comment]
> Исправил. Возникали ли еще какие нибудь ошибки кроме `KeyError: 'year'`?

Теперь возникает ошибка
File "/home/***/yamusic/yandex-music-downloader/main.py", line 108, in from_json
    url_template = 'https://' + json['ogImage']
KeyError: 'ogImage'

Спасибо Вам за то, что вы работаете над своим детищем

**Comment by llistochek** [comment]
Пришлите ссылку на плейлист который вы пытаетесь скачать.

**Comment by Catangenss** [comment]
Не хочу светить профилем, который у яндекса напрямую привязан к никнейму. Могу отправить в лс или на почту.
Только что тестировал, самый большой плейлист, что нашел - 466 треков, 30 ч 3 м -  https://music.yandex.ru/users/music-blog/playlists/2438. Переваривает его без проблем.
Мой плейлист - 3180 треков - 204,5 ч выдает ошибку (предыдущую ошибку отловить не вышло):

Traceback (most recent call last):
  File "/home/***/yamusic/yandex-music-downloader/main.py", line 389, in <module>
    result_tracks = get_playlist(session, args.playlist_id)
  File "/home/***/yamusic/yandex-music-downloader/main.py", line 231, in get_playlist
    tracks = [t for t in tracks if t is not None]
  File "/home/***/yamusic/yandex-music-downloader/main.py", line 231, in <listcomp>
    tracks = [t for t in tracks if t is not None]
  File "/home/***/yamusic/yandex-music-downloader/main.py", line 99, in from_json
    album_json = json['albums'][0]
IndexError: list index out of range

**Comment by llistochek** [comment]
Можете скинуть плейлист мне [на почту](mailto:me@llistochek.ru) или в [телеграм](https://t.me/llistochek).

**Comment by Catangenss** [comment]
Отправил

**Comment by llistochek** [comment]
Исправил

**Comment by llistochek** [comment]
Проблема была исправлена. Если возникнут еще какие нибудь неполадки - открывайте новую issue
