### ISSUE TITLE
Фильтрация символов в имени файла

### ISSUE THREAD

**Issue by alucarD1701** [llistochek/yandex-music-downloader#12]
При скачивании треков, у которых в названии есть символы запрещенные windows для использования в имени файлов выдает ошибку

21:21:55 |INFO| Загружается Within Temptation\Hydra (Deluxe Edition)\4 - Paradise (What About Us?) (feat. Tarja).mp3
Traceback (most recent call last):
  File "C:\Users\Admin\Documents\yandex-music-downloader\main.py", line 416, in <module>
    download_file(session, url, save_path)
  File "C:\Users\Admin\Documents\yandex-music-downloader\main.py", line 194, in download_file
    with open(path, 'wb') as f:
         ^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'Within Temptation\\Hydra (Deluxe Edition)\\4 - Paradise (What About Us?) (feat. Tarja).mp3'

Как я понимаю, функция prepare_track_path на 245 строке должна, в том числе, избавляться от этих символов, но не отрабатывает корректно.(257 и 258 строки по вопросом)

**Comment by llistochek** [comment]
Вы передаете аргумент `--strict-path`?

**Comment by alucarD1701** [comment]
Точно, извините, не заметил что есть такой аргумент. Возможно его стоит
включить по умолчанию?

пт, 14 апр. 2023 г., 02:30 Lev ***@***.***>:

**Comment by llistochek** [comment]
Ок, подумаю насчет включения опции по умолчанию
