### ISSUE TITLE
Предложение - добавить ссылку на трек в тег URL

### ISSUE THREAD

**Issue by alibek2023** [llistochek/yandex-music-downloader#19]
На мой взгляд, если скрипт будет сохранять в теге URL ссылку на трек в Яндекс.Музыке, это будет удобно.

Также есть просьба добавить заполнители (placeholder) #track_id, #album_id, #artist_id, чтобы их можно было использовать для указания подкаталога/файла.

**Comment by llistochek** [comment]
> На мой взгляд, если скрипт будет сохранять в теге URL ссылку на трек в Яндекс.Музыке, это будет удобно.
Вы имеете ввиду сохранение ссылки на трек в теге ID3?

**Comment by alibek2023** [comment]
Да.
Например перед строкой 294 `tag.encoded_by = ENCODED_BY` добавить что-то вроде `tag.url = "https://music.yandex.ru/album/{track.artist[0].id}/track/{track.id}"`, только работающее.
