### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by spownc** [llistochek/yandex-music-downloader#2]
Привет, не удается запустить, ругается на синтаксис:
`E:\temp\Download_ym\yandex-music-downloader>python main.py --session-id "3:1669460013.5.0.1665941275674:1E5Isg:2f.1.2:1|10853484.0.2|3:10261727.163411.LJ_CY9XugF56LM63lMRuQdZCqnc" --hq --dir "/music/BFG" --path-pattern "#artist - #title" --user-agent "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.5304.88 Safari/537.36" --url "https://music.yandex.ru/users/spownc/playlists/1055" --playlist-id "https://music.yandex.ru/users/spownc/playlists/1055"
  File "main.py", line 36
    owner: str
         ^
SyntaxError: invalid syntax`

Что я делаю не правильно?

**Comment by llistochek** [comment]
Какую вы используете версию Python?

**Comment by spownc** [comment]
Windows 10 
Python 2.7.16

**Comment by llistochek** [comment]
Данный скрипт не поддерживает Python 2.x. Используйте Python версии 3.8 и выше.
Также я заметил что вы передаете параметеры `--url` и `--playlist-id` вместе. Так делать не надо, достаточно просто указать `--url`

**Comment by spownc** [comment]
Обновил Python, теперь новые ошибки:
![image](https://user-images.githubusercontent.com/946096/204128781-817293fe-c8bf-412f-b62f-59e3bb2aadeb.png)

**Comment by spownc** [comment]
Использовал куки "sessionid2" вместо указанных "Session_id" - треки начали скачиваться.

**Comment by llistochek** [comment]
У меня не получилось воспроизвести проблему на Windows 10, Python 3.11. Я использовал  обычный `Session_id`, треки скачивались нормально. Посмотрю насчет `sessionid2`, может лучше использовать его.
Проблему решена, issue закрываю. Спасибо за использование скрипта

**Comment by spownc** [comment]
Решение не работает, по "sessionid2" скачиваются демки треков в низком качестве.

**Comment by llistochek** [comment]
Скачиваются ли другие треки/плейлисты или проблема только с этим плейлистом?

**Comment by spownc** [comment]
Никакие не скачиваются. Проверял так же несуществующий лист, проблема та же.

**Comment by llistochek** [comment]
Добавил вывод отладочной информации. Загрузите новую версию скрипта и  добавьте аргумент `--log-level DEBUG`. Будет выведено большое кол-во информации, так что лучше сохранить ее в файл (добавьте `> log.txt` в конец команды которую вы выполняете). Получившийся файл `log.txt`  можете отправить [мне на почту](mailto:me@llistochek.ru) или загрузить на сервис для обмена файлов и скинуть ссылку.

**Comment by spownc** [comment]
Удалось запустить так:
`python main.py --session-id "3: ...9887" --hq --add-lyrics --url "https://music.yandex.ru/users/spownc/playlists/1052" --path-pattern "#artist - #title" --log-level DEBUG --dir "music"`

Скачиваются в высоком качестве, без ошибок.
