### ISSUE TITLE
Бинарники

### ISSUE THREAD

**Issue by butaford** [llistochek/yandex-music-downloader#21]
Было бы круто, организовать бинарники в Release :-)

linux: `pyinstaller --onefile /folder/to/yandex-music-downloader/main.py`
windows: `pyinstaller --onefile --icon="folder\to\icon\yadownload.ico" folder\to\yandex-music-downloader-main\main.py`

собрано: [03470a7](https://github.com/llistochek/yandex-music-downloader/commit/03470a7402546a85b5800e92a32cefdba767c484)
[yadownload_win_x64.zip](https://github.com/llistochek/yandex-music-downloader/files/12251375/yadownload_win_x64.zip)
[yadownload_linux_x64.gz](https://github.com/llistochek/yandex-music-downloader/files/12251383/yadownload_linux_x64.gz)
[yadownload_linux_armv7l.gz](https://github.com/llistochek/yandex-music-downloader/files/12252456/yadownload_linux_armv7l.gz)

Issue без смысловой нагрузки, можно и закрыть.

**Comment by llistochek** [comment]
Не будет реализовано. Не вижу смысла собирать бинарники.
