### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ArtemBay** [llistochek/yandex-music-downloader#25]
Сижу с мака и пытаюсь скачать музыку, но получил такую ошибку. В плейлисте есть песни загруженные через веб версию (те их нет в самом яндексе) и также песни которые были заблокированы 
```py
Traceback (most recent call last):
  File "/Users/artembay/Desktop/YandexMusic_downloader/main.py", line 68, in <module>
    f'{"".join([x if x.isalnum() or x in chars else "" for x in track.get("artists")[0]["name"]])} - ' \
```
Также прилагаю скриншот с полной ошибкой 
<img width="579" alt="image" src="https://github.com/llistochek/yandex-music-downloader/assets/31122393/ab0f2859-b1a0-4a01-9f03-d4d65c01431a">

**Comment by llistochek** [comment]
Вы ошиблись проектом. Откройте issue в https://github.com/MarshalX/yandex-music-api
