### ISSUE TITLE
Не работает --skip-existing

### ISSUE THREAD

**Issue by Loginlag** [llistochek/yandex-music-downloader#27]
`yandex-music-downloader --hq --embed-cover --delay "8" --only-music --playlist-id "myname/3" --dir "F:\music\yandex-music" --path-pattern "#artist - #title" --session-id "myid"`

через некоторое время ловлю `ошибку 400`, жду N кол-во времени и перезапускаю скрипт, музыка качается заново и падает на одном и том же месте видимо из-за большого кол-ва запросов.

проблема: при попытке использовать параметр `--skip-existing` я получаю кол-во треков и на этом всё.

**Comment by llistochek** [comment]
Хотелось бы получить ссылку на ваш плейлист (или минимально необходимый для воспроизведения проблемы плейлист). Без ссылки я не смогу определить причину проблемы. Можете выслать мне ее на [почту](mailto:me@llistochek.ru) или в [телеграм](https://t.me/llistochek).

**Comment by Loginlag** [comment]
Спасибо за ответ. Отправил ссылку на свой плейлист на вашу почту.

**Comment by llistochek** [comment]
Исправил проблему с `--skip-existing`.
Для обновления вызовите следующую команду:
`pip install -U git+https://github.com/llistochek/yandex-music-downloader`

**Comment by llistochek** [comment]
На данный момент я работаю над решением проблемы с ошибкой 400. Вы можете подписаться на issue #24 для отслеживания прогресса.
Спасибо за issue.
