### ISSUE TITLE
Частая ошибка 400 (Session_id недостаточно?)

### ISSUE THREAD

**Issue by brachna** [llistochek/yandex-music-downloader#29]
Здравствуйте. Заметил что очень быстро и часто появляется ошибка 400. Читал рекомендации, но ни капчи ни куки spravka нет.
Для себя ситуацию решил расширением cookies.txt и редактированием.
В core.py добавил:
```
import http
from requests.utils import cookiejar_from_dict, dict_from_cookiejar
```
В setup_session() добавил:
```
cookies = http.cookiejar.MozillaCookieJar()
cookies.load(filename='cookies.txt', ignore_expires=True)
session.cookies = cookiejar_from_dict(dict_from_cookiejar(cookies))
```
Теперь код 400 встречается не так часто а капча и spravka появляются.
Думаю с browser-cookie3 обновлять куки будет еще проще.

**Comment by llistochek** [comment]
Я разобрался с тем, как работает капча от Яндекса. В скором времени будет завершена реструктуризация проекта и, [согласно плану](https://github.com/llistochek/yandex-music-downloader/issues/30), я приступлю к реализации встроенного распознавания капчи. Ошибка 400 больше не будет доставлять проблем.

**Comment by llistochek** [comment]
Исправлено в 8d095450b0ec70bb508f62a3a049e70f9b3a17b9
