### ISSUE TITLE
[V2] Будущее проекта

### ISSUE THREAD

**Issue by llistochek** [llistochek/yandex-music-downloader#30]
На Яндексе размещены далеко не все нужные мне треки. В связи с этим я планирую сделать из данного проекта универсальный загрузчик музыки.
### Задачи
- [ ] Реструктуризация проекта
- [ ] Встроенное распознавание капчи (ручное/с помощью сервисов автоматического распознавания)

После реализации поставленных задач данный проект будет переименован в `universal-music-downloader` и получит версию `2.0.0`. Затем будет реализована загрузка музыки с сервисов, перечисленных ниже.

### Новые сервисы
- [ ] ВКонтакте
- [ ] YouTube
- [ ] Telegram

**Comment by bvn13** [comment]
Во ВКонтакте мало нормальных песен хорошего качества и много фейковых песен. В телеграме есть поиск по файлам? или будет поиск только по выборочным группам?

Предлагаю универсальный вариант - сделать поиск по РуТрекеру.

**Comment by llistochek** [comment]
**Не будет реализовано.**
Подобную проблему (загрузка контента с множества сервисов) решает проект [yt-dlp](https://github.com/yt-dlp/yt-dlp). Не вижу смысла городить еще один велосипед. У yt-dlp есть некоторые проблемы с обработкой метаданных, которые делают его не совсем пригодным для загрузки музыки. Однако мы уже работаем над исправлением этих недочетов.
Что касается данного проекта (yandex-music-downloader), работа над ним продолжится как над загрузчиком музыки именно с Яндекс.Музыки, других сервисов добавлено не будет.
