### ISSUE TITLE
Ошибка при сохранении трека со спец. символами

### ISSUE THREAD

**Issue by Sterh20** [llistochek/yandex-music-downloader#31]
При сохранение файла по маске `"#artist - #title #track-id"` выдает ошибку:
```
File "D:\yandex-music-downloader\ymd\http_utils.py", line 8, in download_file
    with open(path, 'wb') as f:

OSError: [Errno 22] Invalid argument: 'C:\\Music\\James Brown - The Boss (From "Black Caesar" Soundtrack) 53847.mp3'
```
Дело в кавычках в названии [трека](https://music.yandex.ru/album/5721395/track/53847).

Можно добавить стрипинг спец. символов из путей к файлу, которые создает непосредственно библиотека.
Вот [здесь](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) список таких символов для Windows.
[Тут](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) более полный список для всего остального.

Для себя решил заменить название трека на его id.

OS: Windows 10
Python 3.10.11

**Comment by llistochek** [comment]
Очистка от недопустимых символов [уже реализована](https://github.com/llistochek/yandex-music-downloader/blob/45855a7905febb2302df274298ec1a28e0eee279/ymd/core.py#L40). Убедитесь, что вы используете последнюю версию программы и **не передаете** флаг `--unsafe-path`.

**Comment by Sterh20** [comment]
Спасибо. В `--unsafe-path` была проблема.
