### ISSUE TITLE
Загружаются не все треки

### ISSUE THREAD

**Issue by Stmol** [llistochek/yandex-music-downloader#34]
Аргументы запуска:

```bash
yandex-music-downloader \
    --session-id "session_id_string" \
    --only-music \
    --hq \
    --skip-existing \
    --embed-cover \
    --url "$1" \
    --dir "/Users/Username/Downloads/yandex-music-backup/Playlist" \
    --path-pattern "#title - #artist"
```

Дальше запускаю с ссылкой на плейлист:
```bash
dl.sh https://music.yandex.ru/users/username/playlists/9898
```

В стдаут пишет:

```
Треков: 78
```

- Я зашел в плейлист, посчитал, их действительно 78 если исключить те, которые недоступны (но отображаются в интерфейсе)
- По завершению загрузки, я посчитал количество выводов `Загружается .......mp3` в консоли и их тоже 78, то есть загрузка инициировалась честных 78 раз, как и показал счетчик вначале

Но по факту в итоговой директори:

<img width="145" alt="image" src="https://github.com/llistochek/yandex-music-downloader/assets/740892/2201d87b-60e0-4fa1-8b32-5364d294b932">

Есть идеи почему не загрузились 22 трека? Никаких ошибок в процессе работы скрипта не было.

**Comment by llistochek** [comment]
Если проблема для вас еще актуальна - я хотел бы получить ссылку на сам плейлист.
