### ISSUE TITLE
Ошибка при загрузке треков

### ISSUE THREAD

**Issue by Druidblack** [llistochek/yandex-music-downloader#39]
Добрый день. После обновления (где нужно вместо id сессии указывать имя браузера) не могу настроить программу на скачивание треков.

Я использую яндекс браузер. Как я понимаю для него нужно указывать --browser chromium.  Загрузка не заработала.
Пробовал указать куки (использовал этот аддон для их получения https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc?pli=1 )

Итоговая команда получилась такая 
yandex-music-downloader --hq --skip-existing --embed-cover --cover-resolution 1000 --dir /srv/mergerfs/Music/music --browser chromium --cookies-path /srv/config/cookies.txt --url "https://music.yandex.ru/users/Druidblack/playlists/3"

Что нужно еще настроить, что бы работало как и раньше.
![Безымянный](https://github.com/llistochek/yandex-music-downloader/assets/70659424/16e2a902-ffac-4b9c-b88a-a578910fb697)

**Comment by Druidblack** [comment]
Авторизируюсь в Яндекс Браузере на ПК с Windows, а программу запускаю на Linux без графической оболочки.
P.S. Теперь непонятно стало. Авторизоваться нужно на том же пк где и запускаешь программу или нет.
Раньше с указанием id сессии было понятно.

**Comment by Pugemon** [comment]
> Как я понимаю для него нужно указывать --browser chromium
Нет, библиотека для получения куки, не имеет поддержки Yandex Browser
Поэтому используйте другой браузер для этого

И у вас неправильная команда, вам нужно использовать или cookie-path или browser

**Comment by Druidblack** [comment]
Я правильно понимаю. Теперь, что ьы использовать программу для скачивания музыки, нужно ее ставить на Linux с графическим интерфейсом, авторизоваться в браузере (из числа тех, что указанны в хелпе) и потом можно также запускать команду для скачивания музыки.

P.S. Нет вариантов делать две версии? Старый вариант (чисто для командной строки), и новый для тех, кто работает в Linux постоянно.

**Comment by llistochek** [comment]
В `--cookies-path` должен передаваться путь к файлу с куками. Для яндекс браузера это "C:\Users\Пользователь\AppData\Local\Yandex\YandexBrowser\User Data\Default\Cookies". Я не знаю в каком формате яндекс хранит куки, но по идее `--browser chromium` должен подойти.

**Comment by Druidblack** [comment]
Это я уже разобрался. ПРосто я в начале не понял. Раньше для работы только командная строка была нужна. А теперь пришлось ставить виртуалку в нее ставить программу и в ней же запускать браузер, что бы авторизоваться в ЯМ. После этого я кроном запускаю программу, что бы скачивать треки.
В целом то сделали для удобства (теперь не нужно отслеживать когда id сессии помрет).
