### ISSUE TITLE
треки скачиваются по 30 секунд

### ISSUE THREAD

**Issue by anDWIN12** [llistochek/yandex-music-downloader#46]
пользуюсь браузером chrome, дл этого было 2 пользователя

**Comment by llistochek** [comment]
Это проблема с аутентификацией. Можете подробнее рассказать о том, как вы запускаете скрипт?

**Comment by llistochek** [comment]
Закрываю issue из за неактивности. Если захотите сообщить подробности - откройте ее еще раз
