### ISSUE TITLE
Не загружает треки из созданных мною плейлистов

### ISSUE THREAD

**Issue by G1fi** [llistochek/yandex-music-downloader#5]
Проблема идентична -> #2 
Программа прекрасно отрабатывает на альбомах, отдельных треках, плейлистах генерированных самой Яндекс.Музыкой, но не с моими плейлистами

Я пробую:
`python3 main.py --session-id "3:1<...>Lc" --hq --skip-existing --embed-cover --strict-path --url "https://music.yandex.ru/users/nphne-jcskcdkb/playlists/104"`

Я получаю:
```
Traceback (most recent call last):
  File "/home/gifi/yandex-music-downloader/main.py", line 341, in <module>
    result_tracks = get_playlist(session, args.playlist_id)
  File "/home/gifi/yandex-music-downloader/main.py", line 189, in get_playlist
    return [BasicTrackInfo.from_json(t) for t in raw_tracks]
  File "/home/gifi/yandex-music-downloader/main.py", line 189, in <listcomp>
    return [BasicTrackInfo.from_json(t) for t in raw_tracks]
  File "/home/gifi/yandex-music-downloader/main.py", line 73, in from_json
    album_json = json['albums'][0]
IndexError: list index out of range
```

Я ожидаю: нормальную работу программы

**Comment by G1fi** [comment]
[Вывод с аргументом --log-level DEBUG:](https://gist.github.com/G1fi/b8bc0478dc732178e6ce7dd6b6b8fac7)

**Comment by G1fi** [comment]
Смог восстановить работу программы создав копию плейлиста и удалив из него недоступные к прослушиванию песни:
![изображение](https://user-images.githubusercontent.com/60535081/210074155-8e3c0dae-64f2-4517-82a9-719987464343.png)
Если проблема была действительно в этом, чтобы пофиксить баг, нужно сделать отсеивание таких треков.

**Comment by llistochek** [comment]
Да, действительно, для треков которые недоступны на площадке не возвращается информация об альбоме и скрипт крашится. Исправлю это. Спасибо за issue

**Comment by llistochek** [comment]
Исправлено в 0ca6f76119c54961716eed1aaaef27fb921669e6
