### ISSUE TITLE
Длительность трека 30 секунд

### ISSUE THREAD

**Issue by kubada** [llistochek/yandex-music-downloader#51]
macOS 12.7.5
Safari 17.5 (17618.2.12.111.5, 17618)

скачивались все треки из указанного плейлиста, но каждый длительностью 30 секунд.
ошибок не было, оказалось, что нет доступа к файлу с куками.

в указанной версии macOS "~/Library/Cookies/Cookies.binarycookies" пустой, теперь куки хранятся в "~/Library/Containers/com.apple.Safari/Data/Library/Cookies/Cookies.binarycookies" либо "~/Library/Containers/com.apple.Safari/Data/Library/WebKit/WebsiteDataStore/%ID%/Cookies/Cookies.binarycookies".

Добавив эти пути в список `safari_cookies` ~1025 строка файла ~/.venv/lib/python3.12/site-packages/browser_cookie3/__init__.py треки стали загружаться целиком.

**Comment by llistochek** [comment]
Откройте issue в репозитории [browser_cookie3](https://github.com/borisbabic/browser_cookie3/issues). В качестве временного решения можете передавать путь к cookies в параметре `--cookies-path`, например:
`--cookies-path "~/Library/Containers/com.apple.Safari/Data/Library/WebKit/WebsiteDataStore/%ID%/Cookies/Cookies.binarycookies"`.
Спасибо за issue.
