### ISSUE TITLE
Треки не скачиваются

### ISSUE THREAD

**Issue by anDWIN12** [llistochek/yandex-music-downloader#53]
python -d ymd --hq --skip-existing --add-lyrics --embed-cover --url "https://music.yandex.kz/users/Dmitriyqazaq/playlists/3" --dir "C:/Users/User/Desktop/ymd/music" --browser chrome --cookies-path "C:/Users/User/AppData/Local/Google/Chrome/User Data/Profile 5/Network/Cookies"
Треков: 1496
Загружается C:\Users\User\Desktop\ymd\music\cccp edits - Hare_ Krishna.mp3
Код ошибки: 404

**Comment by llistochek** [comment]
Скорее всего проблема в домене. Залил коммит с исправлением (f22cece). Обновите скрипт и попробуйте скачать плейлист еще раз

**Comment by llistochek** [comment]
Закрываю из-за отсутствия активности. Если вы сможете предоставить информацию по работоспособности исправления - откройте issue заново. Спасибо.
