### ISSUE TITLE
MacOS + Yandex Browser. Ошибка "Не удалось получить cookies для браузера"

### ISSUE THREAD

**Issue by archytector** [llistochek/yandex-music-downloader#55]
Добрый вечер!
На MacOS пытаюсь запустить скрипт. Ни один из подходящих вариантов значения ключа `--browser` не помогают.
Указал прямой путь к файлу `/Users/user/Library/Application Support/Yandex/YandexBrowser/Default/Cookies`, попробовал подходящие варианты ключа `--browser`: chrome, chromium, opera. Всегда одна и та же ошибка.
Можно ли вернуть обратно возможность авторизоваться через `--session-id`? Или какую-то подсказку, какая комбинация ключей нужна имеен для Yandex Browser? Или явно указать, что этот браузер пока не поддерживается.

**Comment by llistochek** [comment]
Яндекс браузер видимо использует свою систему хранения cookies. В качестве временного решения можете установаить любой из поддерживаемых браузеров и войти в нем. Я подумаю над реализацией поддержки яндекс браузера и насчет возврата `--session-id`.

**Comment by llistochek** [comment]
В коммите cc472b21f7e5b0fc70d7015a99837dd10230e5fa реализована авторизация через мобильный токен. Обновите скрипт через `pip install -U git+https://github.com/llistochek/yandex-music-downloader`. Если возникнут проблемы при авторизации/скачивании треков - откройте новую issue.
