### ISSUE TITLE
Не устанавливается на Win 11 x64 (Python 3.12.5)

### ISSUE THREAD

**Issue by sattera1** [llistochek/yandex-music-downloader#56]
Не устанавливается на Win 11 x64 (Python 3.12.5)

PS C:\Users\UserName> pip install git+https://github.com/llistochek/yandex-music-downloader
Collecting git+https://github.com/llistochek/yandex-music-downloader
  Cloning https://github.com/llistochek/yandex-music-downloader to c:\users\UserName\appdata\local\temp\pip-req-build-4q1vnjuh
  ERROR: Error [WinError 2] Не удается найти указанный файл while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by llistochek** [comment]
Вам нужно установить git - https://git-scm.com/download/win

**Comment by sattera1** [comment]
Спасибо, помогло! Можно добавить в описание установки.
