### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by vladimeliss** [llistochek/yandex-music-downloader#58]
Добрый день. Делаю скрипт в chrome. Команда такая:

yandex-music-downloader --browser "chrome" --hq --cookies-path "C:\Users\1\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies" --url "https://music.yandex.ru/users/юзер/playlists/номер"

Скрипт завершается сообщением: 

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\1\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Network\\Cookies'

Запускал сначала без параметра cookies, результат тот же...

**Comment by llistochek** [comment]
Это проблема с библиотекой browser_cookie3 (https://github.com/borisbabic/browser_cookie3/issues/180). Попробуйте закрыть браузер и попробовать еще раз

**Comment by sattera1** [comment]
У меня такая же проблема. Если закрыть браузер Chrome и запустить скачивание, все работает

**Comment by Rodion1337** [comment]
Доброго времени суток.

Пробовал открывать хром с флагом ` --disable-features=LockProfileCookieDatabase` и закрывать... результат единый:

![image](https://github.com/user-attachments/assets/31151993-cac9-41ff-ad16-977a3a1e361b)

**Comment by AlexeyQ13** [comment]
Присоединяюсь к проблеме. Пытался указывать браузер один, другой, открывать Chrome с флагом (сообщение выше), указывать путь до файла, копировать целиком папку в другое место и уже туда указывать путь, получать полный доступ над папкой и повышать права для выполнения скрипта - одно и тоже, не работает. Пока не нашёл решение проблемы.

**Comment by llistochek** [comment]
В коммите cc472b21f7e5b0fc70d7015a99837dd10230e5fa реализована авторизация через мобильный токен. Обновите скрипт через `pip install -U git+https://github.com/llistochek/yandex-music-downloader`. Если возникнут проблемы при авторизации/скачивании треков - откройте новую issue.
