### ISSUE TITLE
Ability to download lossless audio

### ISSUE THREAD

**Issue by sburavtsov** [llistochek/yandex-music-downloader#59]
Starting Aug 7 YM providing lossless audio quality.
Can you please implement parameter to be able to download it too?

**Comment by llistochek** [comment]
Да, было бы неплохо реализовать загрузку lossless треков. Но для этого потребуется значительно изменить скрипт:
1. Перейти на мобильный API (https://github.com/MarshalX/yandex-music-api). Как следствие, нужно будет переработать процесс аутентификации. Возможно яндекс музыка реализует поддержку lossless в браузерной версии (что маловероятно), тогда реализация данного пункта не потребуется.
2. Использовать mutagen вместо eyeD3 для проставления тегов.

Я буду следить за новостями о поддержке lossless в браузерной версии и за ходом реализации поддержки lossless  в yandex-music-api (https://github.com/MarshalX/yandex-music-api/issues/656).

**Comment by sattera1** [comment]
Да, поддержка flac'ов будет потрясающей опцией

**Comment by dim2603** [comment]
есть еще десктопный клиент на электроне, помимо мобильного клиента

**Comment by vitaly-zdanevich** [comment]
Но не для Linux.

**Comment by Druidblack** [comment]
В новом интерфейсе (который по адресу next.music.yandex.ru появился вариант выбора превосходного качества звука.

**Comment by llistochek** [comment]
Новый интерфейс использует тот же API, что и мобильное приложение (api.music.yandex.ru). Все таки придется переделывать скрипт под новый API с помощью библиотеки yandex-music-api

**Comment by llistochek** [comment]
Реализовано в 922ead406bce2e1ebeec8a8b5f68645dc06fc8a7

**Comment by llistochek** [comment]
Я ошибся, `--quality 2` нужно ставить
