### ISSUE TITLE
The script does not work when ipv6 is enabled

### ISSUE THREAD

**Issue by Druidblack** [llistochek/yandex-music-downloader#61]
Good afternoon. I found a problem. (it may not be related to your program). When ipv6 is enabled in the system. The script is not working. Does not download music. It hangs for a long time at startup, then returns a 401 or 500 error.
I disabled ipv6 in the system, rebooted, and the program started working.

**Comment by llistochek** [comment]
Возможно это проблема с настройками вашей сети. Открываются ли у вас другие сайты, использующие ipv6?

**Comment by Druidblack** [comment]
Открываются. Я же захожу на яндекс музыку. Да и в целом доступ к сайтам по ipv6 работает.

**Comment by llistochek** [comment]
Исправлено в 72d7c694579c0b5c27b16dc6a6591316ce7ec747. Если проблема сохраняется - откройте issue заново. Спасибо.
