### ISSUE TITLE
Ошибка 400

### ISSUE THREAD

**Issue by dmvProjects** [llistochek/yandex-music-downloader#62]
Первый раз ошибка вылезла после скачивания примерно 50 треков.
Действительно, в браузере понадобилась капча. После нее на время все снова качается ок.
Но спустя еще треков 30 снова 400, но капчи на сайте уже не просит, прослушивание в браузере работает нормально. 
При перезапуске качает 1 трек и снова 400.
Пробовал увеличить тайм-аут до минуты - не помогло.
kubuntu , firefox

**Comment by umihesh** [comment]
Такая же проблема

**Comment by umihesh** [comment]
> Первый раз ошибка вылезла после скачивания примерно 50 треков. Действительно, в браузере понадобилась капча. После нее на время все снова качается ок. Но спустя еще треков 30 снова 400, но капчи на сайте уже не просит, прослушивание в браузере работает нормально. При перезапуске качает 1 трек и снова 400. Пробовал увеличить тайм-аут до минуты - не помогло. kubuntu , firefox

Наблюдаю такую же проблему. Мне помогло переподключить ВПН. Вероятно, Яндекс временно банит IP

**Comment by llistochek** [comment]
В коммите cc472b21f7e5b0fc70d7015a99837dd10230e5fa реализована авторизация через мобильный токен. Обновите скрипт через `pip install -U git+https://github.com/llistochek/yandex-music-downloader`. Если возникнут проблемы при авторизации/скачивании треков - откройте новую issue.
