### ISSUE TITLE
Errno 13

### ISSUE THREAD

**Issue by Rodion1337** [llistochek/yandex-music-downloader#64]
Доброго времени суток.

Может кто-то знает в чем дело?
`yandex-music-downloader --browser "chrome" --hq --skip-existing --dir "E:\python_test\yandex_music" --url "https://music.yandex.ru/album/11644078/track/6705392"`
![image](https://github.com/user-attachments/assets/df7edc08-4da2-4a24-89b6-35492312646c)

**Comment by vitaly-zdanevich** [comment]
Похоже нет пермишена на чтение папки Хрома.

Логи лучше прикреплять не картинкой а текстом - чтобы находилось.

**Comment by vitaly-zdanevich** [comment]
Дубликат https://github.com/llistochek/yandex-music-downloader/issues/58
