### ISSUE TITLE
Не удалось получить cookies для браузера chrome

### ISSUE THREAD

**Issue by QuaiGoner** [llistochek/yandex-music-downloader#66]
Добрый день!

Хром запущен с флагом  --disable-features=LockProfileCookieDatabase. Проблема повторяется и с Edge,
Запускаю через: 
yandex-music-downloader --browser "chrome" --skip-existing --embed-cover --hq --only-music --playlist-id "<ACCOUNT>/3" --dir "<DIR>\yandex_export\" --cookies-path "C:\Users\<User>l\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"

Но всегда ошибка:
Не удалось получить cookies для браузера chrome

**Comment by llistochek** [comment]
В коммите cc472b21f7e5b0fc70d7015a99837dd10230e5fa реализована авторизация через мобильный токен. Обновите скрипт через `pip install -U git+https://github.com/llistochek/yandex-music-downloader`. Если возникнут проблемы при авторизации/скачивании треков - откройте новую issue.
