### ISSUE TITLE
Не найти скрипт при установке через pip

### ISSUE THREAD

**Issue by nickolai** [llistochek/yandex-music-downloader#72]
На Ubuntu 22.04 LTS установил скрипт при помощи pip:

`pip install git+https://github.com/llistochek/yandex-music-downloader`

В результате при попытке запуска команды
`
yandex-music-downloader --help`

Выдаёт ошибку:

> yandex-music-downloader: command not found

Куда установился скрипт? Не могу его найти.

**Comment by llistochek** [comment]
Скорее всего вам нужно добавить `~/.local/bin` в `$PATH`:
https://stackoverflow.com/a/59436732

**Comment by llistochek** [comment]
Закрываю из за неактивности. Откройте issue заново, если проблема сохранилась

**Comment by nickolai** [comment]
~/.local/bin, похоже, не существует:

ls ~/.local/bin
ls: cannot access '/home/user/.local/bin': No such file or directory
