### ISSUE TITLE
перестала работать функция --skip-existing

### ISSUE THREAD

**Issue by Druidblack** [llistochek/yandex-music-downloader#74]
Сегодня утром установил [v3.2.0b1](https://github.com/llistochek/yandex-music-downloader/releases/tag/v3.2.0b1) 
У меня каждый два часа запускается

yandex-music-downloader --quality 1 --add-lyrics --skip-existing --embed-cover --cover-resolution original --dir /mnt/musya --token "AgAAA3lLpjij1FFUQ" --url "https://music.yandex.ru/users/666/playlists/3"

Сейчас обратил внимание, что мне приходили весь день уведомления о скачивании одних и тех же треков.
И у песен из плейлиста скаченных, дата изменения сейчас стоит 18-00 (поменялась с 16-00). И так каждые два часа с 7 утра. То есть треки точно были идентичны весь день.

В прошлой версии такой проблемы не было.

Откатился до версии [v3.0.0b1](https://github.com/llistochek/yandex-music-downloader/releases/tag/v3.0.0b1) (спасибо за описание как это сделать). Программа при запуске той же команды (кроме размера обложки) пропускает скаченные треки.

**Comment by llistochek** [comment]
Исправлено в 0639ea15fce3c86bc60cbc76fcd494805c7b4426. Спасибо за issue
