### ISSUE TITLE
--embed-cover производит неподдерживаемые картинки

### ISSUE THREAD

**Issue by Str1ker17** [llistochek/yandex-music-downloader#77]
Windows Media Player вместо обложки альбома показывает чёрную картинку
Lister (mmedia) плагин в Total Commander просто крашится)
При этом, физически файл с обложкой и без обложки различаются на ~50 кб (то есть выглядит всё легально)

**Comment by llistochek** [comment]
В каком формате вы скачиваете треки?

**Comment by Str1ker17** [comment]
MP3 320 kbps

**Comment by amythiz** [comment]
Вроде поняла: некоторые обложки - это почему-то png файлы, а сохраняются они все как jpg. Если переименовать сломанную обложку (скачанную без --embed-cover, она сломана будет и без него) в .png и добавить её к файлу (через vlc, например), то всё работает.
Что интересно, пример от @Str1ker17 у меня работает нормально, а вот тут уже чёрная обложка (но чинящаяся переименованием в png и передобавлением):
`yandex-music-downloader --token "" --quality 2 --url "https://music.yandex.ru/album/33932956/track/132724618"`

**Comment by Str1ker17** [comment]
Хорошо, можете сделать в питоновском коде, чтобы обложка автоматически конвертилась из png в jpg?

**Comment by amythiz** [comment]
Костыльненький фикс, которым воспользовалась я. Не проверяет изначальный формат обложки и конвертирует всё подряд, но особо сильных замедлений работы вроде нет. Фиксит только для `--embed-cover`

Заменить `cover = covers_cache[album_id] = cover_bytes` в core.py на:
```
image = Image.open(io.BytesIO(cover_bytes))
if image.mode != 'RGB':
    image = image.convert('RGB')
jpg_buffer = io.BytesIO()
image.save(jpg_buffer, 'JPEG', quality=90)  # Качество 0-100
jpg_binary_data = jpg_buffer.getvalue()
cover = covers_cache[album_id] = jpg_binary_data
```
В начале core.py добавить:
```
from PIL import Image
import io
```
Установить PIL, если не установлен.

**Comment by llistochek** [comment]
Исправлено в v3.3.0b0. Откройте issues заново если проблема сохранилась
