### ISSUE TITLE
При отсутствии FLAC скачивается AAC 256kbps вместо MP3 320kbps.

### ISSUE THREAD

**Issue by amythiz** [llistochek/yandex-music-downloader#83]
Например при скачивании https://music.yandex.ru/album/6554988/track/29174897 с параметром `--quality 1` скачивается MP3 320kbps, но при `--quality 2` скачивается AAC 256kbps.
Как я понимаю, AAC 256 хуже по качеству, чем MP3 320, соответственно при отсутствии FLAC должен скачиваться второй.

**Comment by vitaly-zdanevich** [comment]
> AAC 256 хуже по качеству, чем MP3 320

Не уверен.

**Comment by amythiz** [comment]
> Не уверен.
Почитала про AAC, походу да, он будет лучше (и точно не хуже). Но если всё работает корректно, тогда странновато поведения самой ЯМузыки. Получается, что для некоторых треков включение превосходного качества будет потреблять меньше трафика чем оптимальное (AAC 256kbps файлы весят меньше чем MP3 320). Почему AAC 256kbps находится в списке lossless форматов, но отсутствует в списке обычных? Но это уже вопросы к Яндексу. Но в загрузчике не помешала бы возможность получения AAC 256kbps при установленном `--quality 1`

**Comment by llistochek** [comment]
Не будет релизовано. Не вижу смысла усложнять логику, AAC 256 по сути не отличим от MP3 320
