### ISSUE TITLE
Несколько вопросов

### ISSUE THREAD

**Issue by Darkloke** [llistochek/yandex-music-downloader#86]
Добрый день. Несколько вопросов, если позволите (это конечно не очень наверное подходит для issues, но раздела discussions у вас тут нет). Давно пытаюсь найти аналогичную утилиту под Tidal, но всё пока никак - тут появилась возможность затестить ваш аналог под yandex. Решить попробовать и заодно спросить насчёт функционала, который есть в аналогичных утилитах под Tidal.

1. В программе нет часом файла конфигурации, чтобы можно было некоторые параметры забить туда и не вставлять каждый раз в командую строку?
2. Если для альбома lossless недоступен, можно ли какой-то командой пропускать (не скачивать) такие альбомы?
3. Вопрос насчёт метаданных (тэгов) в конечных файлах. Там отсутствует например информация о writer/composer и label в то время как на сайте она присутствует в разделе "About the track" (см. изображение). Можно ли её как-то добавить в файлы?
4. Одновременная загрузка несколько файлов в принципе возможна или строго по одному?
5. Параметр "--skip-existing" сравнивает имеющийся файл только по имени или как-то ещё? Я к тому, что если допустим альбом обновился на сайте, программа перекачает его или скипнет?
5. Есть ли какой-то способ отслеживать зафейленные загрузки (например в случае сетевых сбоев)? Ну например качаем целиком дискографию артиста и по итогу несколько треков не скачались - можно ли как-то это быстро отследить и докачать недостающее? Например в [Tidal-Media-Downloader](https://github.com/yaronzz/Tidal-Media-Downloader) приходилось анализировать лог скачанного на предмет ошибок, а вот [streamrip](https://github.com/nathom/streamrip) формирует аж целую базу данных, где отслеживает такие сбои и потом через отдельный параметр можно перекачать сбойное.
6. Сами FLACи берутся напрямую с серверов или же программа делает конверсию в процессе?

Спасибо и извините, если вопросов много. :)
 
![image](https://github.com/user-attachments/assets/912252d3-d63f-4631-84e8-8ba5df488060)
![image](https://github.com/user-attachments/assets/29090a7f-8fd2-430d-8003-7ce1282c92d8)

**Comment by llistochek** [comment]
1) Конфигурации на данный момент нету, в будущем возможно добавлю. Вы можете написать скрипт, который вызывает программу с нужными вам аргументами, чтобы каждый раз не копировать команду.
2) Нельзя, и реализовано такое не будет.
3) Откройте issue если вам нужен подобный функционал.
4) Нет. Не вижу смысла в этом
5) `--skip-existing` сравнивает файл по имени
6) Треки пропускаются только если они недоступны для скачивания, в случае сетевого сбоя програма крашится. См. #80.
7) FLAC берется напрямую с сервера
