### ISSUE TITLE
Поддержка названий папок с пробелами в начале и конце

### ISSUE THREAD

**Issue by dashke** [llistochek/yandex-music-downloader#88]
При попытке загрузить или обработать файлы в папках с пробелами в начале или конце названия скрипт выдает следующую ошибку:
`FileNotFoundError: [Errno 2] No such file or directory: 'сборник\\I Love Italy \\8 - Mambo Italiano.m4a'`
Перед выполнением операций с файлами/папками, скрипт может автоматически обрабатывать их названия - заменять пробелы на символ **_** для совместимости.

**Comment by llistochek** [comment]
По идее пробелы не должны вызывать проблем. Какие аргументы вы передаете скрипту?

**Comment by llistochek** [comment]
Исправлено в f093365b13f697f7708f3a7428257eeb7f217ef5
